import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { AssessmentResult } from '@/types/assessment';
import { getAssessmentConfig } from './assessments/registry';

/**
 * 生成评测报告 PDF
 * 支持多种评测类型
 */
export const generatePDF = (assessment: AssessmentResult) => {
    const config = getAssessmentConfig(assessment.assessmentType);
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // 获取评测类型名称
    const assessmentName = config?.name || 'Assessment';
    const targetLabel = config?.targetEntity || 'Target';
    const targetName = assessment.targetName || assessment.friendName || 'N/A';

    // Add header
    doc.setFontSize(20);
    doc.text(`${assessmentName} Report`, pageWidth / 2, 20, { align: 'center' });

    // Add basic information
    doc.setFontSize(12);
    doc.text(`Date: ${format(new Date(assessment.date), 'MMMM d, yyyy')}`, 20, 40);
    doc.text(`${targetLabel}: ${targetName}`, 20, 50);
    doc.text(`Overall Score: ${Math.round(assessment.overallScore)}%`, 20, 60);

    // Add assessment message
    doc.setFontSize(14);
    doc.text('Assessment', 20, 80);
    doc.setFontSize(12);
    doc.text(assessment.assessment.message, 20, 90);
    doc.text(assessment.assessment.recommendation, 20, 100);

    // Add category scores
    doc.setFontSize(14);
    doc.text('Category Scores', 20, 120);
    doc.setFontSize(12);

    let yPosition = 130;
    Object.entries(assessment.categoryScores).forEach(([category, score]) => {
        if (yPosition > 250) {
            doc.addPage();
            yPosition = 20;
        }
        doc.text(`${category}: ${Math.round(score)}%`, 20, yPosition);
        yPosition += 10;
    });

    // Add notes if any
    if (assessment.notes) {
        yPosition += 10;
        if (yPosition > 250) {
            doc.addPage();
            yPosition = 20;
        }
        doc.setFontSize(14);
        doc.text('Notes', 20, yPosition);
        doc.setFontSize(12);
        doc.text(assessment.notes, 20, yPosition + 10);
    }

    // Add footer
    doc.setFontSize(10);
    doc.text('Generated by FriendScope', pageWidth / 2, 280, { align: 'center' });

    // Save the PDF
    doc.save(`${assessmentName.replace(/\s+/g, '-')}-${targetName}-${format(new Date(assessment.date), 'yyyy-MM-dd')}.pdf`);
};

/**
 * 分享评测结果
 * 支持多种评测类型
 */
export const shareAssessment = async (assessment: AssessmentResult) => {
    const config = getAssessmentConfig(assessment.assessmentType);
    const assessmentName = config?.name || 'Assessment';
    const targetName = assessment.targetName || assessment.friendName || 'N/A';

    const shareData = {
        title: `${assessmentName} Results`,
        text: `Check out my ${assessmentName.toLowerCase()} with ${targetName}! Overall Score: ${Math.round(assessment.overallScore)}%`,
        url: window.location.href
    };

    try {
        if (navigator.share) {
            await navigator.share(shareData);
            return true;
        }
        return false;
    } catch (error) {
        console.error('Error sharing:', error);
        return false;
    }
};
